apiVersion: batch/v1
kind: CronJob
metadata:
  name: juniperstablecoinnewsdev
  namespace: 'ictd-oi-juniper-dev'
spec:
  schedule: "50 23 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: juniper-stable-coins-news-dev
              image: $IMAGE_NAME
              imagePullPolicy: "Always"
              env:
              - name: DB_NAME
                value: juniper
              - name: DB_URL
                valueFrom:
                  secretKeyRef:
                    name: juniper-secrets-dev
                    key: DB_URL
          restartPolicy: Never